Add a missing dependency of 'ar' when building with code coverage.
The 'gcov' library is required. Otherwise, the linking fails with

    error: undefined reference to `__gcov_init'